
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------
require("monitors")


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

hl.on("hyprland.start", function ()
    hl.exec_cmd("mpvpaper")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("ags run")
 end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------
local home = os.getenv("HOME")
local colors = dofile(home .. "/.cache/wal/colors.lua")

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 2,
        gaps_out = 4,

        border_size = 2,

        col = {
            active_border   = { colors = {colors.color12, colors.color14}, angle = 45 },
            inactive_border = { colors = {colors.color9, colors.color10}, angle = 45 },
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    group = {
        col = {
            border_active           = { colors = { colors.color12, colors.color14 }, angle = 45 },
            border_inactive         = { colors = { colors.color9,  colors.color10 }, angle = 45 },
            border_locked_active    = { colors = { colors.color12, colors.color14 }, angle = 45 },
            border_locked_inactive  = { colors = { colors.color9,  colors.color10 }, angle = 45 },
        }
    },


    decoration = {
        rounding       = 6,
        rounding_power = 4,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 0.9,
        inactive_opacity = 0.8,

        shadow = {
            enabled      = false,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 5,
            passes    = 3,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
        
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })

hl.curve("mybezier",       { type = "bezier", points = { {0.22, 1},    {0.36, 1}     } })
hl.curve("mybezierIn",     { type = "bezier", points = { {0.16, 1},    {0.3, 1}      } })
hl.curve("mybezierOut",    { type = "bezier", points = { {0.4, 0},     {1, 0.7}      } })
hl.animation({ leaf = "windows",    enabled = true, speed = 4.8, bezier = "mybezier",       style = "slide" })
hl.animation({ leaf = "windowsIn",  enabled = true, speed = 4.5, bezier = "mybezierIn",     style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.8, bezier = "mybezierOut",    style = "slide" })


hl.curve("fadeInSmooth",  { type = "bezier", points = { {0.25, 0},    {0.5, 1}      } })
hl.curve("fadeOutSmooth", { type = "bezier", points = { {0.4, 0},     {0.8, 0.5}    } })
hl.curve("fadeSmooth",    { type = "bezier", points = { {0.25, 0.1},  {0.25, 1}    } })
hl.animation({ leaf = "fadeIn",  enabled = true, speed = 2.4, bezier = "fadeInSmooth"  })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 2.0, bezier = "fadeOutSmooth" })
hl.animation({ leaf = "fade",    enabled = true, speed = 3.2, bezier = "fadeSmooth"    })


hl.curve("layerSmooth",    { type = "bezier", points = { {0.22, 1},   {0.36, 1}   } })
hl.curve("layerIn",        { type = "bezier", points = { {0.16, 1},   {0.3, 1}    } })
hl.curve("layerOut",       { type = "bezier", points = { {0.4, 0},    {1, 0.7}     } })
hl.curve("layerFadeIn",    { type = "bezier", points = { {0.25, 0},   {0.5, 1}    } })
hl.curve("layerFadeOut",   { type = "bezier", points = { {0.4, 0},    {0.8, 0.5}  } })
hl.animation({ leaf = "layers",        enabled = true, speed = 4.2, bezier = "layerSmooth" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4.5, bezier = "layerIn",      style = "slide left" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 2.8, bezier = "layerOut",     style = "slide right" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 2.4, bezier = "layerFadeIn" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 2.0, bezier = "layerFadeOut" })

hl.curve("workspaceSmooth", { type = "bezier", points = { {0.22, 1},   {0.36, 1}   } })
hl.curve("workspaceIn",     { type = "bezier", points = { {0.16, 1},   {0.3, 1}    } })
hl.curve("workspaceOut",    { type = "bezier", points = { {0.4, 0},    {1, 0.7}     } })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 3.8, bezier = "workspaceSmooth", style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 3.6, bezier = "workspaceIn",     style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 3.0, bezier = "workspaceOut",    style = "slide" })

hl.curve("zoomSmooth", { type = "bezier", points = { {0.25, 0.1}, {0.25, 1} } })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 6.5, bezier = "zoomSmooth" })

hl.curve("borderLoop", { type = "bezier", points = { {0, 0}, {1, 1} } })
hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "borderLoop", style = "loop" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "latam",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0.3, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})
hl.gesture({
    fingers = 4,
    direction = "right",
    action = function () rofi_menu_anim_global("~/.config/WallpaperSelector/wallpaper.sh") end
})
hl.gesture({
    fingers = 4,
    direction = "left",
    action = function() toggle_ags_widget_anim("slide right", "toggle") end
})
hl.gesture({
    fingers = 3,
    direction = "vertical",
    action = function () rofi_menu_anim("slide bottom", "rofi -show drun") end
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------
require("keybinds")

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
require("rules")
