##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Quitar transparecia de YouTube
windowrule {
    name = firefox
    match:title = (.*)(- YouTube)(.*)
    opacity = 1.0 override 1.0 override
}

# Regla para blur en programs especificos
layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, ignore_alpha 0.1
layerrule = match:namespace logout_dialog, blur on

# Regla para blur en programs especificos
#layerrule = match:namespace rofi, blur on
#layerrule = match:namespace rofi, ignore_alpha 0.1
#layerrule = match:namespace logout_dialog, blur on
#layerrule = match:namespace eww, blur on
#layerrule = match:namespace eww, ignore_alpha 0.1

#layerrule = match:namespace gtk-layer-shell, blur on
#layerrule = match:namespace gtk-layer-shell, ignore_alpha 0.1

#windowrule = match:class ^(codium)$, opacity 1.1 1.0

#para panel de arriba
#layerrule = match:namespace ^(eww-control-panel)$, animation slide right
#layerrule = match:namespace ^(eww-control-panel)$, blur on
#layerrule = match:namespace ^(eww-control-panel)$, ignore_alpha 0.1
#layerrule = match:namespace rofi, animation slide bottom